name = "GuidedProposals"
uuid = "2d53f948-c29b-4abe-a473-2cf2f1798516"
authors = ["Sebastiano Grazzi", "Frank van der Meulen", "Marcin Mider", "Moritz Schauer"]
version = "0.1.0"

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffObservScheme = "a6ddd3f2-050f-41aa-9a1f-1d4f9243493f"
DiffusionDefinition = "c126fcb9-5a08-4fee-b75a-97eb446288b0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.3"

[extras]
DiffObservScheme = "a6ddd3f2-050f-41aa-9a1f-1d4f9243493f"
DiffusionDefinition = "c126fcb9-5a08-4fee-b75a-97eb446288b0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff", "Random", "DiffObservScheme", "DiffusionDefinition"]
